import { CompanyRegistrationRequestDetail } from "@/types/company"

export const MOCK_REQUEST_DETAILS: Record<string, CompanyRegistrationRequestDetail> = {
  "1": {
    id: "1",
    hrName: "Nguyễn Thị Mai",
    phone: "0901 234 567",
    email: "mai.nguyen@acme.com",
    companyName: "Acme Technology JSC",
    websiteUrl: "acme.com",
    status: "chờ xét duyệt",
    createdAt: "2026-06-15T08:30:00Z",
    companyType: "Công nghệ thông tin",
    country: "Việt Nam",
    teamSize: "100-500 nhân viên",
    overview: "<b>Kiểm tra các format</b><div><i>in nghiêng.</i></div><div><ul><li><b><i>1</i></b></li><li><b><i>2</i></b></li><li><b><i>3</i></b></li></ul><ol><li><b><i>a</i></b></li><li><b><i>b</i></b></li><li><b><i>c</i></b></li><li><b><i>d</i></b></li></ol></div>",
    taxCode: "0100109106",
  },
  "2": {
    id: "2",
    hrName: "Trần Văn Hùng",
    phone: "0912 345 678",
    email: "hung.tran@fintechvn.io",
    companyName: "FintechVN",
    websiteUrl: "fintechvn.io",
    status: "chờ xét duyệt",
    createdAt: "2026-06-15T09:15:00Z",
    companyType: "Tài chính / Ngân hàng",
    country: "Việt Nam",
    teamSize: "50-100 nhân viên",
    overview: "<p>FintechVN chuyên cung cấp các giải pháp thanh toán điện tử và ví điện tử thế hệ mới.</p>",
    taxCode: "0316794479",
  },
  "3": {
    id: "3",
    hrName: "Lê Minh Khoa",
    phone: "0933 456 789",
    email: "khoa.le@globalsoft.co",
    companyName: "GlobalSoft Co. Ltd",
    websiteUrl: "globalsoft.co",
    status: "đã duyệt",
    createdAt: "2026-06-14T14:20:00Z",
    companyType: "Outsourcing",
    country: "Việt Nam",
    teamSize: "500-1000 nhân viên",
    overview: "<p>GlobalSoft cung cấp dịch vụ gia công phần mềm chất lượng cao cho thị trường Nhật Bản và Mỹ.</p>",
    taxCode: "0102030405",
  },
  "4": {
    id: "4",
    hrName: "Phạm Thu Hà",
    phone: "0944 567 890",
    email: "ha.pham@eduviet.edu.vn",
    companyName: "EduViet",
    websiteUrl: "eduviet.edu.vn",
    status: "chờ xét duyệt",
    createdAt: "2026-06-15T11:00:00Z",
    companyType: "Giáo dục / Đào tạo",
    country: "Việt Nam",
    teamSize: "10-50 nhân viên",
    overview: "<p>Hệ thống đào tạo trực tuyến dành cho học sinh phổ thông và ôn thi đại học.</p>",
    taxCode: "0106883582",
  },
  "5": {
    id: "5",
    hrName: "Hoàng Đức Anh",
    phone: "0955 678 901",
    email: "anh.hoang@b2bpro.vn",
    companyName: "B2B Pro Vietnam",
    websiteUrl: "b2bpro.vn",
    status: "chờ xét duyệt",
    createdAt: "2026-06-15T13:45:00Z",
    companyType: "Thương mại điện tử",
    country: "Việt Nam",
    teamSize: "50-100 nhân viên",
    overview: "<b>Kiểm tra các format</b><div><i>in nghiêng.</i></div><div><ul><li><b><i>1</i></b></li><li><b><i>2</i></b></li><li><b><i>3</i></b></li></ul><ol><li><b><i>a</i></b></li><li><b><i>b</i></b></li><li><b><i>c</i></b></li><li><b><i>d</i></b></li></ol></div>",
    taxCode: "0314209538",
  },
  "6": {
    id: "6",
    hrName: "Vũ Thị Lan",
    phone: "0966 789 012",
    email: "lan.vu@healthtechsg.com",
    companyName: "HealthTech SG",
    websiteUrl: "healthtechsg.com",
    status: "chờ xét duyệt",
    createdAt: "2026-06-15T15:20:00Z",
    companyType: "Y tế / Sức khỏe",
    country: "Singapore",
    teamSize: "10-50 nhân viên",
    overview: "<p>Cung cấp ứng dụng chăm sóc sức khỏe chủ động và tư vấn bác sĩ từ xa.</p>",
    taxCode: "1234567890",
  },
  "7": {
    id: "7",
    hrName: "Đinh Quang Minh",
    phone: "0977 890 123",
    email: "dinhquangminh240804@gmail.com",
    companyName: "Game Studio VN",
    websiteUrl: "gamestudio.gg",
    status: "đã duyệt",
    createdAt: "2026-06-13T10:10:00Z",
    companyType: "Giải trí / Game",
    country: "Việt Nam",
    teamSize: "50-100 nhân viên",
    overview: "<p>Studio phát triển game di động với nhiều sản phẩm đạt top tải về trên Google Play và App Store.</p>",
    taxCode: "0109553641",
  },
  "8": {
    id: "8",
    hrName: "Bùi Thanh Tâm",
    phone: "0988 901 234",
    email: "tam.bui@consulting.co",
    companyName: "Tam Consulting",
    websiteUrl: "tamconsulting.co",
    status: "chờ xét duyệt",
    createdAt: "2025-05-17T16:40:00Z",
    companyType: "Consulting",
    country: "Việt Nam",
    teamSize: "1–10 nhân viên",
    overview: "<p>Công ty tư vấn nhỏ cần tuyển 2-3 vị trí.</p>",
    taxCode: "0100109106",
  },
  "9": {
    id: "9",
    hrName: "Phan Anh Tuấn",
    phone: "0911 222 333",
    email: "tuan.phan@logistics.vn",
    companyName: "V-Logistics",
    websiteUrl: "vlogistics.vn",
    status: "chờ xét duyệt",
    createdAt: "2026-06-15T17:10:00Z",
    companyType: "Vận chuyển / Kho vận",
    country: "Việt Nam",
    teamSize: "100-500 nhân viên",
    overview: "<p>Dịch vụ giao hàng chặng cuối và quản lý chuỗi cung ứng thông minh tại Việt Nam.</p>",
    taxCode: "0313589410",
  },
  "10": {
    id: "10",
    hrName: "Ngô Quốc Bảo",
    phone: "0922 333 444",
    email: "bao.ngo@retailone.com",
    companyName: "Retail One",
    websiteUrl: "retailone.com",
    status: "đã duyệt",
    createdAt: "2026-06-12T09:00:00Z",
    companyType: "Bán lẻ / Tiêu dùng",
    country: "Việt Nam",
    teamSize: "500-1000 nhân viên",
    overview: "<p>Chuỗi siêu thị tiện lợi phủ khắp các tỉnh thành miền Bắc và miền Trung.</p>",
    taxCode: "0108549321",
  },
}
