
import { CompanyRegistrationRequest } from "@/types/company";

export const INITIAL_MOCK_DATA: CompanyRegistrationRequest[] = [
  {
    id: "1",
    hrName: "Nguyễn Thị Mai",
    phone: "0901 234 567",
    email: "mai.nguyen@acme.com",
    companyName: "Acme Technology JSC",
    websiteUrl: "acme.com",
    status: "chờ xét duyệt",
    createdAt: "2026-06-15T08:30:00Z",
  },
  {
    id: "2",
    hrName: "Trần Văn Hùng",
    phone: "0912 345 678",
    email: "hung.tran@fintechvn.io",
    companyName: "FintechVN",
    websiteUrl: "fintechvn.io",
    status: "chờ xét duyệt",
    createdAt: "2026-06-15T09:15:00Z",
  },
  {
    id: "3",
    hrName: "Lê Minh Khoa",
    phone: "0933 456 789",
    email: "khoa.le@globalsoft.co",
    companyName: "GlobalSoft Co. Ltd",
    websiteUrl: "globalsoft.co",
    status: "đã duyệt",
    createdAt: "2026-06-14T14:20:00Z",
  },
  {
    id: "4",
    hrName: "Phạm Thu Hà",
    phone: "0944 567 890",
    email: "ha.pham@eduviet.edu.vn",
    companyName: "EduViet",
    websiteUrl: "eduviet.edu.vn",
    status: "chờ xét duyệt",
    createdAt: "2026-06-15T11:00:00Z",
  },
  {
    id: "5",
    hrName: "Hoàng Đức Anh",
    phone: "0955 678 901",
    email: "anh.hoang@b2bpro.vn",
    companyName: "B2B Pro Vietnam",
    websiteUrl: "b2bpro.vn",
    status: "chờ xét duyệt",
    createdAt: "2026-06-15T13:45:00Z",
  },
  {
    id: "6",
    hrName: "Vũ Thị Lan",
    phone: "0966 789 012",
    email: "lan.vu@healthtechsg.com",
    companyName: "HealthTech SG",
    websiteUrl: "healthtechsg.com",
    status: "chờ xét duyệt",
    createdAt: "2026-06-15T15:20:00Z",
  },
  {
    id: "7",
    hrName: "Đinh Quang Minh",
    phone: "0977 890 123",
    email: "quangminh.dinh@gamestudio.gg",
    companyName: "Game Studio VN",
    websiteUrl: "gamestudio.gg",
    status: "đã duyệt",
    createdAt: "2026-06-13T10:10:00Z",
  },
  {
    id: "8",
    hrName: "Bùi Thanh Tâm",
    phone: "0988 901 234",
    email: "tam.bui@consulting.co",
    companyName: "Tam Consulting",
    websiteUrl: "tamconsulting.co",
    status: "chờ xét duyệt",
    createdAt: "2026-06-15T16:40:00Z",
  },
  {
    id: "9",
    hrName: "Phan Anh Tuấn",
    phone: "0911 222 333",
    email: "tuan.phan@logistics.vn",
    companyName: "V-Logistics",
    websiteUrl: "vlogistics.vn",
    status: "chờ xét duyệt",
    createdAt: "2026-06-15T17:10:00Z",
  },
  {
    id: "10",
    hrName: "Ngô Quốc Bảo",
    phone: "0922 333 444",
    email: "bao.ngo@retailone.com",
    companyName: "Retail One",
    websiteUrl: "retailone.com",
    status: "đã duyệt",
    createdAt: "2026-06-12T09:00:00Z",
  },
]
